name: animanager
description: "Aplicación móvil para el sistema AniManager: gestión de tareas, reportes y notificaciones para trabajadores."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Animaciones
  lottie: ^3.1.0
  animations: ^2.0.8

  # Iconos modernos
  flutter_vector_icons: ^2.0.0
  ionicons: ^0.2.2

  # Fechas, formato y utilidades
  intl: ^0.19.0

  # Widgets modernos y estilizados
  flutter_slidable: ^3.1.0
  awesome_notifications: ^0.9.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/vaca.json
    # - assets/lottie/notification.json
